socket_access_token: "YOUR_SOCKET_ACCESS_TOKEN"

# Commands for each event type
events:
  twitch_account:
    follow:
      - "say %player% was followed on Twitch!"
    subscription:
      - "give %player% minecraft:diamond 1"
  youtube_account:
    follow:
      - "say %player% was followed on YouTube!"
    subscription:
      - "give %player% minecraft:golden_apple 1"
    superchat:
      - "say %player% received a YouTube Superchat!"
  streamlabs:
    donation:
      - "say %player% received a donation!"

# Custom chat commands
chat_commands:
  "!creeper": "summon creeper %player%"
  "!sheep": "summon sheep %player%"

execute_policy: "random"  # Options: random, all, inline